import { Deal, OutputAsset, UploadTemplate } from "@/lib/types";

export const standardTags = [
  "Revenue",
  "COGS",
  "Gross Profit",
  "Operating Expenses",
  "EBITDA",
  "ARR",
  "Net Revenue Retention",
  "Customer Churn",
  "Headcount",
  "CapEx",
] as const;

export const uploadTemplates: UploadTemplate[] = [
  {
    id: "tpl-1",
    name: "FY24_Quality_of_Earnings.xlsx",
    fileType: "XLSX",
    detectedCategory: "Financials",
    status: "Connected",
  },
  {
    id: "tpl-2",
    name: "Monthly_KPI_Pack_Jan-Dec_2024.pdf",
    fileType: "PDF",
    detectedCategory: "KPI Reports",
    status: "Connected",
  },
  {
    id: "tpl-3",
    name: "Top_50_Customers_Q4_2024.csv",
    fileType: "CSV",
    detectedCategory: "Customer Data",
    status: "Connected",
  },
  {
    id: "tpl-4",
    name: "Data_Room_Index_v12.docx",
    fileType: "DOCX",
    detectedCategory: "Legal / Misc",
    status: "Indexed",
  },
];

function findFileName(deal: Deal, sourceFileId: string) {
  return deal.sourceFiles.find((file) => file.id === sourceFileId)?.name ?? "Unknown file";
}

function tableOutput(
  id: string,
  name: string,
  status: OutputAsset["status"],
  generatedDate: string,
  completeness: number,
  sourceLinked: boolean,
  reviewStatus: string,
  rows: OutputAsset["previewRows"],
): OutputAsset {
  return {
    id,
    name,
    status,
    generatedDate,
    completeness,
    sourceLinked,
    reviewStatus,
    previewType: "table",
    previewRows: rows,
  };
}

function sectionOutput(
  id: string,
  name: string,
  status: OutputAsset["status"],
  generatedDate: string,
  completeness: number,
  sourceLinked: boolean,
  reviewStatus: string,
  sections: OutputAsset["previewSections"],
): OutputAsset {
  return {
    id,
    name,
    status,
    generatedDate,
    completeness,
    sourceLinked,
    reviewStatus,
    previewType: "sections",
    previewSections: sections,
  };
}

export const deals: Deal[] = [
  {
    id: "northstar-software",
    targetCompanyName: "Northstar Vertical Software",
    sector: "Vertical SaaS",
    status: "Review",
    sourceFilesConnected: true,
    extractionProgress: 92,
    exceptionCount: 4,
    outputsReady: true,
    seller: "Founder-led recap",
    sponsor: "Westbridge Capital",
    geography: "US & Canada",
    stage: "Management presentation complete",
    enterpriseValue: 485_000_000,
    ttmRevenue: 78_400_000,
    ttmEbitda: 23_100_000,
    readinessScore: 88,
    workflowProgress: 84,
    recentActivity: [
      {
        id: "ns-act-1",
        title: "Customer concentration support refreshed",
        description: "Q4 cohort file replaced with signed-off finance export and trace links were preserved.",
        timestamp: "2026-03-31T14:20:00.000Z",
      },
      {
        id: "ns-act-2",
        title: "Low-confidence gross margin item resolved",
        description: "Services implementation labor reclassed from OpEx to COGS based on QoE page 18.",
        timestamp: "2026-03-31T11:05:00.000Z",
      },
      {
        id: "ns-act-3",
        title: "P&L workbook regenerated",
        description: "Version 7 completed with updated FY2024 trace comments and review notes package.",
        timestamp: "2026-03-30T18:10:00.000Z",
      },
    ],
    sourceFiles: [
      {
        id: "ns-file-1",
        name: "Northstar_QoE_Final.xlsx",
        fileType: "XLSX",
        uploadDate: "2026-03-28T15:00:00.000Z",
        detectedCategory: "Financials",
        status: "Indexed",
        pages: 14,
        owner: "Deal team",
      },
      {
        id: "ns-file-2",
        name: "Board_Pack_Dec_2025.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-28T15:04:00.000Z",
        detectedCategory: "KPI Reports",
        status: "Indexed",
        pages: 72,
        owner: "CFO",
      },
      {
        id: "ns-file-3",
        name: "Customer_Concentration_Q4_2025.csv",
        fileType: "CSV",
        uploadDate: "2026-03-28T15:07:00.000Z",
        detectedCategory: "Customer Data",
        status: "Connected",
        pages: 1,
        owner: "RevOps",
      },
      {
        id: "ns-file-4",
        name: "Data_Room_Request_List.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-28T15:11:00.000Z",
        detectedCategory: "Legal / Misc",
        status: "Connected",
        pages: 11,
        owner: "Banker",
      },
    ],
    extractedItems: [
      {
        id: "ns-ext-1",
        title: "FY2024 P&L",
        sourceFileId: "ns-file-1",
        period: "FY2024A",
        confidence: 96,
        detectedTableType: "Income Statement",
        issueFlags: ["None"],
        summary: "Full-year management P&L with monthly detail and adjusted EBITDA bridge.",
      },
      {
        id: "ns-ext-2",
        title: "Monthly revenue bridge",
        sourceFileId: "ns-file-2",
        period: "Jan-Dec 2025",
        confidence: 89,
        detectedTableType: "Bridge Analysis",
        issueFlags: ["Unit ambiguity"],
        summary: "Recurring revenue bridge by new, expansion, contraction, and churn motions.",
      },
      {
        id: "ns-ext-3",
        title: "Customer concentration table",
        sourceFileId: "ns-file-3",
        period: "Q4 2025",
        confidence: 93,
        detectedTableType: "Concentration",
        issueFlags: ["None"],
        summary: "Top 20 customers with ARR, share of revenue, and contract renewal dates.",
      },
      {
        id: "ns-ext-4",
        title: "Headcount by department",
        sourceFileId: "ns-file-2",
        period: "Dec 2025",
        confidence: 81,
        detectedTableType: "Workforce",
        issueFlags: ["Missing headers"],
        summary: "Department-level FTE table reconstructed from board pack appendix.",
      },
    ],
    mappingRows: [
      {
        id: "ns-map-1",
        sourceFileId: "ns-file-1",
        sourceLocator: "QoE tab P&L!B12",
        rawLineItemLabel: "Subscription revenue",
        rawValue: "$62.4m",
        period: "FY2024A",
        mappedCategory: "Revenue",
        confidence: 98,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Primary recurring software revenue line with direct tie to management P&L.",
      },
      {
        id: "ns-map-2",
        sourceFileId: "ns-file-1",
        sourceLocator: "QoE tab P&L!B18",
        rawLineItemLabel: "Implementation services labor",
        rawValue: "$6.1m",
        period: "FY2024A",
        mappedCategory: "COGS",
        confidence: 87,
        sourceLinked: true,
        status: "Rule Applied",
        reasoning: "Direct delivery labor tied to services revenue and should sit above gross profit.",
      },
      {
        id: "ns-map-3",
        sourceFileId: "ns-file-1",
        sourceLocator: "QoE tab P&L!B21",
        rawLineItemLabel: "Gross profit",
        rawValue: "$48.8m",
        period: "FY2024A",
        mappedCategory: "Gross Profit",
        confidence: 99,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Calculated subtotal already present in the source and reconciles to revenue less COGS.",
      },
      {
        id: "ns-map-4",
        sourceFileId: "ns-file-2",
        sourceLocator: "Board pack p.19",
        rawLineItemLabel: "Sales & marketing",
        rawValue: "$11.7m",
        period: "FY2024A",
        mappedCategory: "Operating Expenses",
        confidence: 92,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Board pack classification matches opex bucket used in databook template.",
      },
      {
        id: "ns-map-5",
        sourceFileId: "ns-file-1",
        sourceLocator: "QoE tab P&L!B31",
        rawLineItemLabel: "Adjusted EBITDA",
        rawValue: "$23.1m",
        period: "FY2024A",
        mappedCategory: "EBITDA",
        confidence: 97,
        sourceLinked: true,
        status: "Approved",
        reasoning: "QoE adjusted EBITDA line is the agreed benchmark metric for the deal team.",
      },
      {
        id: "ns-map-6",
        sourceFileId: "ns-file-3",
        sourceLocator: "Customer file row 12",
        rawLineItemLabel: "Annual recurring revenue",
        rawValue: "$64.9m",
        period: "FY2025E",
        mappedCategory: "ARR",
        confidence: 86,
        sourceLinked: true,
        status: "Pending",
        reasoning: "ARR rolls up from customer file but needs tie-out to December board pack.",
      },
      {
        id: "ns-map-7",
        sourceFileId: "ns-file-2",
        sourceLocator: "Board pack p.24",
        rawLineItemLabel: "Logo churn",
        rawValue: "4.8%",
        period: "FY2025E",
        mappedCategory: "Customer Churn",
        confidence: 83,
        sourceLinked: true,
        status: "Needs Review",
        reasoning: "Board pack shows logo churn while databook expects revenue churn; needs analyst sign-off.",
      },
      {
        id: "ns-map-8",
        sourceFileId: "ns-file-2",
        sourceLocator: "Board pack appendix p.63",
        rawLineItemLabel: "Total FTE",
        rawValue: "286",
        period: "Dec 2025",
        mappedCategory: "Headcount",
        confidence: 80,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Table is readable but header loss means department breakout should be reviewed.",
      },
    ],
    exceptions: [
      {
        id: "ns-ex-1",
        severity: "High",
        category: "Low confidence mapping",
        affectedLineItem: "Logo churn -> Customer Churn",
        suggestedResolution: "Confirm whether revenue churn or logo churn should populate the databook metric.",
        assignedOwner: "A. Chen",
        status: "Open",
        detail: "Board pack metric is logo churn while databook template labels the field as customer churn.",
      },
      {
        id: "ns-ex-2",
        severity: "Medium",
        category: "Unit mismatch",
        affectedLineItem: "Monthly revenue bridge",
        suggestedResolution: "Standardize board pack monthly table to USD thousands before export.",
        assignedOwner: "J. Miller",
        status: "Open",
        detail: "Bridge table uses $000 notation while QoE file uses full dollars.",
      },
      {
        id: "ns-ex-3",
        severity: "Low",
        category: "Missing source support",
        affectedLineItem: "Department headcount breakout",
        suggestedResolution: "Carry total headcount only and mark department split as pending support.",
        assignedOwner: "Deal Ops",
        status: "Deferred",
        detail: "Appendix image lost one department header during OCR reconstruction.",
      },
      {
        id: "ns-ex-4",
        severity: "Medium",
        category: "Unusual margin change",
        affectedLineItem: "Gross margin FY2024A",
        suggestedResolution: "Retain QoE classification and add review note referencing implementation labor reclass.",
        assignedOwner: "Finance VP",
        status: "Approved",
        detail: "Gross margin expanded 420 bps after services labor moved above gross profit.",
      },
    ],
    outputs: [
      tableOutput(
        "databook-preview",
        "Databook Preview",
        "Ready",
        "2026-03-31T18:02:00.000Z",
        95,
        true,
        "Partner review complete",
        [
          { item: "Revenue", valueA: "$71.2m", valueB: "$78.4m", trace: "QoE tab P&L!B12" },
          { item: "COGS", valueA: "$24.8m", valueB: "$29.6m", trace: "QoE tab P&L!B18" },
          { item: "Gross Profit", valueA: "$46.4m", valueB: "$48.8m", trace: "QoE tab P&L!B21" },
          { item: "EBITDA", valueA: "$19.7m", valueB: "$23.1m", trace: "QoE tab P&L!B31" },
        ],
      ),
      tableOutput(
        "pnl-workbook",
        "P&L Workbook",
        "Ready",
        "2026-03-31T18:05:00.000Z",
        100,
        true,
        "Ready to export",
        [
          { item: "Revenue", valueA: "FY2023A", valueB: "$71.2m", trace: "Source linked" },
          { item: "Revenue", valueA: "FY2024A", valueB: "$78.4m", trace: "Source linked" },
          { item: "EBITDA", valueA: "FY2023A", valueB: "$19.7m", trace: "Source linked" },
          { item: "EBITDA", valueA: "FY2024A", valueB: "$23.1m", trace: "Source linked" },
        ],
      ),
      sectionOutput(
        "ic-prep-notes",
        "IC Prep Notes",
        "Needs Review",
        "2026-03-31T17:42:00.000Z",
        84,
        true,
        "VP review pending",
        [
          {
            heading: "Operating performance",
            bullets: [
              "Recurring software revenue remains above 80% of mix with low customer concentration.",
              "Gross margin uplift reflects implementation labor classification changes flagged in review notes.",
            ],
          },
          {
            heading: "Follow-up items",
            bullets: [
              "Confirm databook churn definition before final IC package.",
              "Collect cleaner department headcount support from finance.",
            ],
          },
        ],
      ),
      sectionOutput(
        "review-notes-package",
        "Review Notes Package",
        "Ready",
        "2026-03-31T17:50:00.000Z",
        92,
        true,
        "Analyst review complete",
        [
          {
            heading: "Open items",
            bullets: [
              "Revenue churn vs logo churn mapping remains open.",
              "Board pack bridge units converted from $000 to full dollars in export layer.",
            ],
          },
        ],
      ),
      sectionOutput(
        "crm-update-package",
        "CRM Update Package",
        "Queued",
        "2026-03-31T17:35:00.000Z",
        68,
        false,
        "Mock only",
        [
          {
            heading: "CRM field payload",
            bullets: [
              "Target: Northstar Vertical Software",
              "Stage: Management presentation complete",
              "Status: Review-ready P&L databook",
            ],
          },
        ],
      ),
    ],
    copilotPrompts: [
      {
        id: "ns-copilot-1",
        label: "Explain why this item was mapped this way",
        response:
          "Implementation services labor was mapped into COGS because it is delivery labor tied directly to services revenue. The QoE workbook also treats this as above-gross-profit cost on the adjusted margin bridge.",
      },
      {
        id: "ns-copilot-2",
        label: "Summarize key exceptions",
        response:
          "Two items still deserve analyst attention: churn definition alignment and department-level headcount support. Neither blocks the P&L workbook, but both should be called out in review notes.",
      },
      {
        id: "ns-copilot-3",
        label: "Draft IC prep notes",
        response:
          "Northstar shows a strong recurring revenue mix, visible margin expansion after cost reclassification, and manageable concentration risk. The remaining diligence point is making sure churn definitions match the databook schema.",
      },
      {
        id: "ns-copilot-4",
        label: "Compare mapped vs source values",
        response:
          "Mapped Revenue, Gross Profit, and EBITDA tie directly to the QoE file. ARR and churn rely on secondary operating reports and are marked with lower confidence accordingly.",
      },
    ],
    qualityPanel: {
      missingHeaders: 1,
      duplicateFiles: 0,
      unreadablePages: 1,
      unitAmbiguity: 1,
      confidenceSummary: {
        high: 5,
        medium: 3,
        low: 0,
      },
    },
  },
  {
    id: "harbor-industrial",
    targetCompanyName: "Harbor Industrial Services",
    sector: "Industrial Services",
    status: "Mapping",
    sourceFilesConnected: true,
    extractionProgress: 78,
    exceptionCount: 9,
    outputsReady: false,
    seller: "Corporate carve-out",
    sponsor: "North Ridge Partners",
    geography: "US Southeast",
    stage: "QoE in process",
    enterpriseValue: 365_000_000,
    ttmRevenue: 132_500_000,
    ttmEbitda: 21_800_000,
    readinessScore: 72,
    workflowProgress: 67,
    recentActivity: [
      {
        id: "hi-act-1",
        title: "Duplicate field service file flagged",
        description: "November operating pack appears twice with conflicting timestamp metadata.",
        timestamp: "2026-03-31T16:05:00.000Z",
      },
      {
        id: "hi-act-2",
        title: "CapEx mapping rule proposed",
        description: "Maintenance vs growth capex split needs analyst confirmation before rule can be saved.",
        timestamp: "2026-03-31T13:11:00.000Z",
      },
    ],
    sourceFiles: [
      {
        id: "hi-file-1",
        name: "Harbor_FY24_QoE_Draft.xlsx",
        fileType: "XLSX",
        uploadDate: "2026-03-29T12:02:00.000Z",
        detectedCategory: "Financials",
        status: "Indexed",
        pages: 18,
        owner: "QoE provider",
      },
      {
        id: "hi-file-2",
        name: "Operating_Pack_Nov_2025.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-29T12:09:00.000Z",
        detectedCategory: "KPI Reports",
        status: "Flagged",
        pages: 44,
        owner: "Operations",
      },
      {
        id: "hi-file-3",
        name: "Top_Customers_FY24.xlsx",
        fileType: "XLSX",
        uploadDate: "2026-03-29T12:15:00.000Z",
        detectedCategory: "Customer Data",
        status: "Connected",
        pages: 6,
        owner: "Controller",
      },
      {
        id: "hi-file-4",
        name: "Lease_and_Litigation_Summary.docx",
        fileType: "DOCX",
        uploadDate: "2026-03-29T12:19:00.000Z",
        detectedCategory: "Legal / Misc",
        status: "Connected",
        pages: 9,
        owner: "Legal",
      },
    ],
    extractedItems: [
      {
        id: "hi-ext-1",
        title: "FY2024 P&L",
        sourceFileId: "hi-file-1",
        period: "FY2024A",
        confidence: 88,
        detectedTableType: "Income Statement",
        issueFlags: ["Duplicate files"],
        summary: "QoE draft contains normalized site-level EBITDA adjustments.",
      },
      {
        id: "hi-ext-2",
        title: "Monthly revenue bridge",
        sourceFileId: "hi-file-2",
        period: "Jan-Nov 2025",
        confidence: 74,
        detectedTableType: "Bridge Analysis",
        issueFlags: ["Unreadable pages", "Unit ambiguity"],
        summary: "Site revenue bridge reconstructed from scanned operating pack tables.",
      },
      {
        id: "hi-ext-3",
        title: "Customer concentration table",
        sourceFileId: "hi-file-3",
        period: "FY2024A",
        confidence: 91,
        detectedTableType: "Concentration",
        issueFlags: ["None"],
        summary: "Top ten industrial customers with margin profile and contract tenor.",
      },
      {
        id: "hi-ext-4",
        title: "Maintenance capex schedule",
        sourceFileId: "hi-file-1",
        period: "FY2024A",
        confidence: 82,
        detectedTableType: "CapEx",
        issueFlags: ["Missing headers"],
        summary: "CapEx table includes field service fleet refresh and facility projects.",
      },
    ],
    mappingRows: [
      {
        id: "hi-map-1",
        sourceFileId: "hi-file-1",
        sourceLocator: "Normalized P&L!C10",
        rawLineItemLabel: "Field service revenue",
        rawValue: "$132.5m",
        period: "FY2024A",
        mappedCategory: "Revenue",
        confidence: 95,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Primary service revenue line with no competing definitions across sources.",
      },
      {
        id: "hi-map-2",
        sourceFileId: "hi-file-1",
        sourceLocator: "Normalized P&L!C15",
        rawLineItemLabel: "Technician wages",
        rawValue: "$61.3m",
        period: "FY2024A",
        mappedCategory: "COGS",
        confidence: 90,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Direct labor for technicians supports revenue delivery and belongs in cost of services.",
      },
      {
        id: "hi-map-3",
        sourceFileId: "hi-file-2",
        sourceLocator: "Operating pack p.16",
        rawLineItemLabel: "Branch overhead",
        rawValue: "$18.9m",
        period: "FY2024A",
        mappedCategory: "Operating Expenses",
        confidence: 76,
        sourceLinked: true,
        status: "Needs Review",
        reasoning: "Could split between direct branch support and corporate overhead if team wants finer granularity.",
      },
      {
        id: "hi-map-4",
        sourceFileId: "hi-file-1",
        sourceLocator: "Normalized P&L!C27",
        rawLineItemLabel: "Adjusted EBITDA",
        rawValue: "$21.8m",
        period: "FY2024A",
        mappedCategory: "EBITDA",
        confidence: 93,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Adjusted EBITDA ties to QoE bridge and lender deck.",
      },
      {
        id: "hi-map-5",
        sourceFileId: "hi-file-2",
        sourceLocator: "Operating pack p.28",
        rawLineItemLabel: "Field headcount",
        rawValue: "412",
        period: "Nov 2025",
        mappedCategory: "Headcount",
        confidence: 78,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Page image is partially blurred, but total headcount still appears usable.",
      },
      {
        id: "hi-map-6",
        sourceFileId: "hi-file-1",
        sourceLocator: "Capex schedule!D14",
        rawLineItemLabel: "Fleet replacement",
        rawValue: "$4.1m",
        period: "FY2024A",
        mappedCategory: "CapEx",
        confidence: 81,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Likely maintenance capex, but table headings are partially truncated.",
      },
    ],
    exceptions: [
      {
        id: "hi-ex-1",
        severity: "Critical",
        category: "Conflicting values between files",
        affectedLineItem: "November revenue bridge",
        suggestedResolution: "Retain finance-issued PDF and exclude older duplicate upload from bridge analysis.",
        assignedOwner: "S. Patel",
        status: "Open",
        detail: "Two operating packs show different November revenue totals by branch.",
      },
      {
        id: "hi-ex-2",
        severity: "High",
        category: "Period mismatch",
        affectedLineItem: "Field headcount",
        suggestedResolution: "Label source as Nov 2025 and avoid backfilling to FY2024A headcount.",
        assignedOwner: "Deal Ops",
        status: "Open",
        detail: "Headcount source is monthly whereas databook line item expects year-end or LTM context.",
      },
      {
        id: "hi-ex-3",
        severity: "Medium",
        category: "Unit mismatch",
        affectedLineItem: "Monthly revenue bridge",
        suggestedResolution: "Convert branch-level tables from $000s to USD before export.",
        assignedOwner: "A. Chen",
        status: "Edited",
        detail: "Bridge table switches notation mid-report between dollars and $000.",
      },
      {
        id: "hi-ex-4",
        severity: "Medium",
        category: "Missing source support",
        affectedLineItem: "Maintenance capex split",
        suggestedResolution: "Keep a single CapEx line until facility project backup arrives.",
        assignedOwner: "J. Miller",
        status: "Deferred",
        detail: "Fleet replacement is supported, but facility project distinction is not.",
      },
    ],
    outputs: [
      tableOutput(
        "databook-preview",
        "Databook Preview",
        "Needs Review",
        "2026-03-31T15:40:00.000Z",
        72,
        true,
        "Exception review open",
        [
          { item: "Revenue", valueA: "$121.4m", valueB: "$132.5m", trace: "Normalized P&L!C10" },
          { item: "COGS", valueA: "$54.2m", valueB: "$61.3m", trace: "Normalized P&L!C15" },
          { item: "EBITDA", valueA: "$18.0m", valueB: "$21.8m", trace: "Normalized P&L!C27" },
        ],
      ),
      tableOutput(
        "pnl-workbook",
        "P&L Workbook",
        "Queued",
        "2026-03-31T15:41:00.000Z",
        58,
        true,
        "Waiting on mapping resolution",
        [
          { item: "Revenue", valueA: "FY2024A", valueB: "$132.5m", trace: "Source linked" },
          { item: "EBITDA", valueA: "FY2024A", valueB: "$21.8m", trace: "Source linked" },
        ],
      ),
      sectionOutput(
        "ic-prep-notes",
        "IC Prep Notes",
        "Queued",
        "2026-03-31T15:41:00.000Z",
        49,
        true,
        "Blocked on review queue",
        [
          {
            heading: "Draft points",
            bullets: [
              "Industrial services model shows healthy branch contribution margins.",
              "Duplicate monthly packs must be resolved before the story is decision-ready.",
            ],
          },
        ],
      ),
      sectionOutput(
        "review-notes-package",
        "Review Notes Package",
        "In Progress",
        "2026-03-31T15:42:00.000Z",
        61,
        true,
        "Analyst drafting",
        [
          {
            heading: "Current notes",
            bullets: [
              "November bridge conflict remains unresolved.",
              "Capex split requires better supporting schedule.",
            ],
          },
        ],
      ),
      sectionOutput(
        "crm-update-package",
        "CRM Update Package",
        "Queued",
        "2026-03-31T15:43:00.000Z",
        35,
        false,
        "Mock only",
        [
          {
            heading: "Staging payload",
            bullets: [
              "Stage: QoE in process",
              "Status: mapping in progress",
            ],
          },
        ],
      ),
    ],
    copilotPrompts: [
      {
        id: "hi-copilot-1",
        label: "Explain why this item was mapped this way",
        response:
          "Technician wages were mapped into COGS because they are direct service delivery costs. The remaining question is whether some branch support labor should be split into operating expenses.",
      },
      {
        id: "hi-copilot-2",
        label: "Summarize key exceptions",
        response:
          "The highest-risk issue is the duplicate November operating pack. Until that is resolved, the monthly bridge and any derived trend commentary should remain provisional.",
      },
      {
        id: "hi-copilot-3",
        label: "Draft IC prep notes",
        response:
          "Harbor has a credible service margin profile and defensible recurring maintenance base, but the workstream still needs tighter support on monthly bridge integrity and capex classification.",
      },
      {
        id: "hi-copilot-4",
        label: "Compare mapped vs source values",
        response:
          "Revenue and EBITDA tie to the QoE draft. Headcount and monthly bridge metrics are supported by lower-quality operating pack pages and remain open for review.",
      },
    ],
    qualityPanel: {
      missingHeaders: 1,
      duplicateFiles: 1,
      unreadablePages: 3,
      unitAmbiguity: 2,
      confidenceSummary: {
        high: 3,
        medium: 3,
        low: 0,
      },
    },
  },
  {
    id: "lattice-health",
    targetCompanyName: "Lattice Health Services",
    sector: "Healthcare Services",
    status: "Extraction",
    sourceFilesConnected: true,
    extractionProgress: 61,
    exceptionCount: 11,
    outputsReady: false,
    seller: "Sponsor exit",
    sponsor: "Alder Point Equity",
    geography: "Midwest",
    stage: "Data room open",
    enterpriseValue: 525_000_000,
    ttmRevenue: 154_800_000,
    ttmEbitda: 28_400_000,
    readinessScore: 63,
    workflowProgress: 48,
    recentActivity: [
      {
        id: "lh-act-1",
        title: "Scanned census report staged",
        description: "Census appendix converted into a draft extraction item for review.",
        timestamp: "2026-03-31T12:40:00.000Z",
      },
      {
        id: "lh-act-2",
        title: "Unit-of-measure warning raised",
        description: "Occupancy report alternates between beds and patient days across quarters.",
        timestamp: "2026-03-31T10:18:00.000Z",
      },
    ],
    sourceFiles: [
      {
        id: "lh-file-1",
        name: "Lattice_Financials_FY22-FY24.xlsx",
        fileType: "XLSX",
        uploadDate: "2026-03-30T09:04:00.000Z",
        detectedCategory: "Financials",
        status: "Indexed",
        pages: 9,
        owner: "Finance",
      },
      {
        id: "lh-file-2",
        name: "Operating_KPI_Pack_Q4_2025.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-30T09:10:00.000Z",
        detectedCategory: "KPI Reports",
        status: "Scanning",
        pages: 58,
        owner: "COO",
      },
      {
        id: "lh-file-3",
        name: "Referral_and_Payer_Mix.csv",
        fileType: "CSV",
        uploadDate: "2026-03-30T09:15:00.000Z",
        detectedCategory: "Customer Data",
        status: "Connected",
        pages: 1,
        owner: "Revenue cycle",
      },
      {
        id: "lh-file-4",
        name: "Compliance_Memo_Summary.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-30T09:18:00.000Z",
        detectedCategory: "Legal / Misc",
        status: "Connected",
        pages: 13,
        owner: "General counsel",
      },
    ],
    extractedItems: [
      {
        id: "lh-ext-1",
        title: "FY2024 P&L",
        sourceFileId: "lh-file-1",
        period: "FY2024A",
        confidence: 90,
        detectedTableType: "Income Statement",
        issueFlags: ["None"],
        summary: "Historical P&L with facility-level roll-up and add-back schedule.",
      },
      {
        id: "lh-ext-2",
        title: "Monthly revenue bridge",
        sourceFileId: "lh-file-2",
        period: "Q1-Q4 2025",
        confidence: 69,
        detectedTableType: "Bridge Analysis",
        issueFlags: ["Unreadable pages", "Unit ambiguity"],
        summary: "Scanned occupancy and revenue bridge with mixed facility annotations.",
      },
      {
        id: "lh-ext-3",
        title: "Payer mix table",
        sourceFileId: "lh-file-3",
        period: "FY2025A",
        confidence: 86,
        detectedTableType: "Payer Mix",
        issueFlags: ["None"],
        summary: "Government, commercial, and private-pay mix by facility cluster.",
      },
      {
        id: "lh-ext-4",
        title: "Headcount by department",
        sourceFileId: "lh-file-2",
        period: "Q4 2025",
        confidence: 72,
        detectedTableType: "Workforce",
        issueFlags: ["Missing headers"],
        summary: "Clinical and administrative staffing table inferred from scanned appendix.",
      },
    ],
    mappingRows: [
      {
        id: "lh-map-1",
        sourceFileId: "lh-file-1",
        sourceLocator: "Historical P&L!D11",
        rawLineItemLabel: "Net patient service revenue",
        rawValue: "$154.8m",
        period: "FY2024A",
        mappedCategory: "Revenue",
        confidence: 94,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Primary revenue line in the financial workbook.",
      },
      {
        id: "lh-map-2",
        sourceFileId: "lh-file-1",
        sourceLocator: "Historical P&L!D18",
        rawLineItemLabel: "Clinical labor",
        rawValue: "$88.2m",
        period: "FY2024A",
        mappedCategory: "COGS",
        confidence: 89,
        sourceLinked: true,
        status: "Approved",
        reasoning: "Direct care labor is treated as cost of service delivery.",
      },
      {
        id: "lh-map-3",
        sourceFileId: "lh-file-2",
        sourceLocator: "KPI pack p.23",
        rawLineItemLabel: "Admissions volume",
        rawValue: "12,460",
        period: "FY2025A",
        mappedCategory: "Revenue",
        confidence: 58,
        sourceLinked: true,
        status: "Needs Review",
        reasoning: "Volume is not a databook P&L line and likely belongs in a KPI appendix later.",
      },
      {
        id: "lh-map-4",
        sourceFileId: "lh-file-2",
        sourceLocator: "KPI pack p.31",
        rawLineItemLabel: "Total employees",
        rawValue: "1,184",
        period: "Q4 2025",
        mappedCategory: "Headcount",
        confidence: 71,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Header loss means employee type categories were partially reconstructed.",
      },
    ],
    exceptions: [
      {
        id: "lh-ex-1",
        severity: "High",
        category: "Period mismatch",
        affectedLineItem: "Admissions volume",
        suggestedResolution: "Keep volume metrics out of the P&L databook tab for MVP scope.",
        assignedOwner: "A. Chen",
        status: "Open",
        detail: "Operational volume is being confused with revenue mapping during staging.",
      },
      {
        id: "lh-ex-2",
        severity: "High",
        category: "Unit mismatch",
        affectedLineItem: "Occupancy bridge",
        suggestedResolution: "Normalize to patient days and add note that source alternates with licensed beds.",
        assignedOwner: "Healthcare associate",
        status: "Open",
        detail: "Quarterly occupancy report flips units by facility cluster.",
      },
      {
        id: "lh-ex-3",
        severity: "Medium",
        category: "Unreadable pages",
        affectedLineItem: "Clinical staffing appendix",
        suggestedResolution: "Restrict export to total headcount until a cleaner PDF is available.",
        assignedOwner: "Deal Ops",
        status: "Deferred",
        detail: "Appendix pages 52-54 are too faint for reliable table reconstruction.",
      },
    ],
    outputs: [
      tableOutput(
        "databook-preview",
        "Databook Preview",
        "Queued",
        "2026-03-31T12:01:00.000Z",
        44,
        true,
        "Extraction not complete",
        [
          { item: "Revenue", valueA: "$149.0m", valueB: "$154.8m", trace: "Historical P&L!D11" },
          { item: "EBITDA", valueA: "$25.1m", valueB: "$28.4m", trace: "Historical P&L add-back bridge" },
        ],
      ),
      tableOutput(
        "pnl-workbook",
        "P&L Workbook",
        "Queued",
        "2026-03-31T12:02:00.000Z",
        32,
        true,
        "Awaiting mapping coverage",
        [
          { item: "Revenue", valueA: "FY2024A", valueB: "$154.8m", trace: "Source linked" },
        ],
      ),
      sectionOutput(
        "ic-prep-notes",
        "IC Prep Notes",
        "Queued",
        "2026-03-31T12:03:00.000Z",
        20,
        false,
        "Not started",
        [
          {
            heading: "Pending",
            bullets: ["IC prep notes will unlock after extraction and mapping coverage improve."],
          },
        ],
      ),
      sectionOutput(
        "review-notes-package",
        "Review Notes Package",
        "In Progress",
        "2026-03-31T12:04:00.000Z",
        46,
        true,
        "Analyst review in progress",
        [
          {
            heading: "Current blockers",
            bullets: [
              "Volume metrics are bleeding into revenue mapping review.",
              "Occupancy units require normalization before output generation.",
            ],
          },
        ],
      ),
      sectionOutput(
        "crm-update-package",
        "CRM Update Package",
        "Queued",
        "2026-03-31T12:05:00.000Z",
        18,
        false,
        "Mock only",
        [
          {
            heading: "Status payload",
            bullets: ["Stage: data room open", "Status: extraction underway"],
          },
        ],
      ),
    ],
    copilotPrompts: [
      {
        id: "lh-copilot-1",
        label: "Explain why this item was mapped this way",
        response:
          "Clinical labor maps to COGS because it is direct care delivery expense. Admissions volume does not belong on the current P&L-focused databook tab and should stay in exception review for now.",
      },
      {
        id: "lh-copilot-2",
        label: "Summarize key exceptions",
        response:
          "The extraction is usable for financial lines, but occupancy units and scanned staffing tables are still too noisy to trust without review. The current scope should stay narrow around the P&L until those are resolved.",
      },
      {
        id: "lh-copilot-3",
        label: "Draft IC prep notes",
        response:
          "Lattice has solid base financial coverage already, but the operating KPI layer still needs cleanup before the team can rely on ancillary metrics in committee materials.",
      },
      {
        id: "lh-copilot-4",
        label: "Compare mapped vs source values",
        response:
          "Historical financial values are well supported by the Excel file. Scanned KPI pack values remain lower confidence and are flagged visibly instead of being forced into the databook.",
      },
    ],
    qualityPanel: {
      missingHeaders: 2,
      duplicateFiles: 0,
      unreadablePages: 4,
      unitAmbiguity: 2,
      confidenceSummary: {
        high: 2,
        medium: 2,
        low: 0,
      },
    },
  },
  {
    id: "summit-logistics",
    targetCompanyName: "Summit Logistics Group",
    sector: "Transportation & Logistics",
    status: "Initial Scan",
    sourceFilesConnected: false,
    extractionProgress: 34,
    exceptionCount: 6,
    outputsReady: false,
    seller: "Founder-owned",
    sponsor: "No sponsor yet",
    geography: "US national",
    stage: "Teaser review",
    enterpriseValue: 290_000_000,
    ttmRevenue: 96_200_000,
    ttmEbitda: 12_900_000,
    readinessScore: 41,
    workflowProgress: 24,
    recentActivity: [
      {
        id: "sl-act-1",
        title: "Initial manifest created",
        description: "Three uploaded files categorized; financial coverage still incomplete.",
        timestamp: "2026-03-31T09:12:00.000Z",
      },
      {
        id: "sl-act-2",
        title: "Readiness score updated",
        description: "Source coverage remains below threshold for mapping launch.",
        timestamp: "2026-03-31T08:44:00.000Z",
      },
    ],
    sourceFiles: [
      {
        id: "sl-file-1",
        name: "Summit_TTM_Financials.xlsx",
        fileType: "XLSX",
        uploadDate: "2026-03-31T08:10:00.000Z",
        detectedCategory: "Financials",
        status: "Connected",
        pages: 6,
        owner: "Management",
      },
      {
        id: "sl-file-2",
        name: "Commercial_Update_Q1_2026.pdf",
        fileType: "PDF",
        uploadDate: "2026-03-31T08:18:00.000Z",
        detectedCategory: "KPI Reports",
        status: "Scanning",
        pages: 32,
        owner: "Sales",
      },
      {
        id: "sl-file-3",
        name: "Customer_Lanes_Report.csv",
        fileType: "CSV",
        uploadDate: "2026-03-31T08:22:00.000Z",
        detectedCategory: "Customer Data",
        status: "Connected",
        pages: 1,
        owner: "Commercial ops",
      },
    ],
    extractedItems: [
      {
        id: "sl-ext-1",
        title: "FY2024 P&L",
        sourceFileId: "sl-file-1",
        period: "FY2024A",
        confidence: 76,
        detectedTableType: "Income Statement",
        issueFlags: ["Missing headers"],
        summary: "TTM workbook missing formal row labels on one contribution margin section.",
      },
      {
        id: "sl-ext-2",
        title: "Customer concentration table",
        sourceFileId: "sl-file-3",
        period: "Q1 2026",
        confidence: 85,
        detectedTableType: "Concentration",
        issueFlags: ["None"],
        summary: "Lane-level customer concentration and gross margin data.",
      },
    ],
    mappingRows: [
      {
        id: "sl-map-1",
        sourceFileId: "sl-file-1",
        sourceLocator: "TTM P&L!B9",
        rawLineItemLabel: "Freight brokerage revenue",
        rawValue: "$96.2m",
        period: "TTM",
        mappedCategory: "Revenue",
        confidence: 84,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Source is good enough for staging, but not yet approved because supporting cost schedule is missing.",
      },
      {
        id: "sl-map-2",
        sourceFileId: "sl-file-1",
        sourceLocator: "TTM P&L!B14",
        rawLineItemLabel: "Purchased transportation",
        rawValue: "$71.4m",
        period: "TTM",
        mappedCategory: "COGS",
        confidence: 80,
        sourceLinked: true,
        status: "Pending",
        reasoning: "Direct pass-through carrier expense, but mapping awaits full monthly support.",
      },
    ],
    exceptions: [
      {
        id: "sl-ex-1",
        severity: "High",
        category: "Missing source support",
        affectedLineItem: "Monthly EBITDA walk",
        suggestedResolution: "Request monthly financial package before launching output generation.",
        assignedOwner: "Deal lead",
        status: "Open",
        detail: "Only TTM summary is available right now.",
      },
      {
        id: "sl-ex-2",
        severity: "Medium",
        category: "Missing headers",
        affectedLineItem: "Contribution margin section",
        suggestedResolution: "Hold split-line mapping until row labels are confirmed with management.",
        assignedOwner: "Analyst",
        status: "Open",
        detail: "One P&L section is unlabeled in the current workbook extract.",
      },
    ],
    outputs: [
      tableOutput(
        "databook-preview",
        "Databook Preview",
        "Queued",
        "2026-03-31T09:20:00.000Z",
        18,
        false,
        "Not ready",
        [
          { item: "Revenue", valueA: "TTM", valueB: "$96.2m", trace: "TTM P&L!B9" },
        ],
      ),
      tableOutput(
        "pnl-workbook",
        "P&L Workbook",
        "Queued",
        "2026-03-31T09:21:00.000Z",
        8,
        false,
        "Not ready",
        [
          { item: "Revenue", valueA: "TTM", valueB: "$96.2m", trace: "Pending full support" },
        ],
      ),
      sectionOutput(
        "ic-prep-notes",
        "IC Prep Notes",
        "Queued",
        "2026-03-31T09:22:00.000Z",
        0,
        false,
        "Not started",
        [
          {
            heading: "Status",
            bullets: ["Additional financial support is required before notes generation."],
          },
        ],
      ),
      sectionOutput(
        "review-notes-package",
        "Review Notes Package",
        "Queued",
        "2026-03-31T09:23:00.000Z",
        12,
        false,
        "Pending extraction",
        [
          {
            heading: "Open requirements",
            bullets: [
              "Monthly EBITDA bridge",
              "Labeled contribution margin rows",
            ],
          },
        ],
      ),
      sectionOutput(
        "crm-update-package",
        "CRM Update Package",
        "Queued",
        "2026-03-31T09:24:00.000Z",
        5,
        false,
        "Mock only",
        [
          {
            heading: "Status payload",
            bullets: ["Stage: teaser review", "Status: initial scan only"],
          },
        ],
      ),
    ],
    copilotPrompts: [
      {
        id: "sl-copilot-1",
        label: "Explain why this item was mapped this way",
        response:
          "Freight brokerage revenue is a clean Revenue line, but the system is intentionally not pretending the rest of the databook is ready without full monthly support.",
      },
      {
        id: "sl-copilot-2",
        label: "Summarize key exceptions",
        response:
          "This deal is still early. The biggest issue is incomplete source coverage, not model confidence. The workflow is stopping at readiness instead of pushing through unreliable outputs.",
      },
      {
        id: "sl-copilot-3",
        label: "Draft IC prep notes",
        response:
          "Too early for credible committee notes. The current recommendation is to request a monthly financial pack and a clean contribution margin schedule before proceeding.",
      },
      {
        id: "sl-copilot-4",
        label: "Compare mapped vs source values",
        response:
          "Only the TTM revenue and direct carrier cost lines are meaningfully mapped so far. Everything else is visibly held back until more support arrives.",
      },
    ],
    qualityPanel: {
      missingHeaders: 2,
      duplicateFiles: 0,
      unreadablePages: 1,
      unitAmbiguity: 1,
      confidenceSummary: {
        high: 1,
        medium: 1,
        low: 0,
      },
    },
  },
];

export function getDeals() {
  return deals;
}

export function getDealById(dealId: string) {
  return deals.find((deal) => deal.id === dealId);
}

export function getOutputById(dealId: string, outputId: string) {
  return getDealById(dealId)?.outputs.find((output) => output.id === outputId);
}

export function getFileName(deal: Deal, sourceFileId: string) {
  return findFileName(deal, sourceFileId);
}
